services:
  service:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pytorch-model
    ports:
      - "5000:5000"
    volumes:
      - app_volume:/app
      - image_volume:/app/image  # 使用 Docker 卷来挂载图片目录


volumes:
    image_volume:
    app_volume: