swagger: "2.0"
info:
  title: Backend API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:

  /predict:
    post:
      tags:
        - all
      summary: predict text
      operationId: server.predict
      parameters:
        - in: body
          name: predict_request
          schema:
            $ref: '#/definitions/PredictRequest'
      responses:
        200:
          description: OK
          schema:
            type: object
  /upload:
    post:
      summary: "Upload an image"
      operationId: server.upload
      consumes:
        - "multipart/form-data"
      parameters:
        - name: file
          in: formData
          required: true
          type: file
      responses:
        200:
          description: "Image uploaded successfully"
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Image uploaded successfully"
              image_path:
                type: string
                example: "/path/to/image.jpg"

  /analyze:
    post:
      summary: "analyze data by llm"
      operationId: server.llm_analyze
      parameters:
      - in: body
        name: analyse_request
        schema:
          $ref: '#/definitions/AnalyseRequest'
      responses:
        200:
          description: ok
          schema:
            type: object





definitions:
  PredictRequest:
    type: object
    properties:
      text:
        type: string
      image:
        type: string
      mode:
        type: string
    required:
      - text
      - image
      - mode

  AnalyseRequest:
    type: object
    properties:
      text:
        type: string
      image:
        type: string
      data:
        type: object



